# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  pod 'Firebase/Database'
  pod 'Firebase/Core'

target 'FIreBaseTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FIreBaseTest

end
