# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxMemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxMemo

  # RxSwift Community Projects
  pod 'NSObject+Rx'
  pod 'RxSwiftExt'
  pod 'Action'
  pod 'RxDataSources'
  pod "RxGesture"
  pod 'RxReachability'
  pod 'RxKeyboard'

  # Networking
  pod 'RxAlamofire'

end
